export const listField = [
  {
    id: 1,
    name: 'slogan',
    hintText: 'Slogan',
    rows: 1,
    rowsMax: 1,
    multiLine: false,
    primaryText: 'Slogan',
  },
  {
    id: 2,
    name: 'register_description',
    hintText: ' Register Description',
    rows: 1,
    rowsMax: 2,
    multiLine: true,
    className: 'multi-row',
    primaryText: 'Register Description',
  },
  {
    id: 3,
    name: 'call_paper_description',
    hintText: ' Call For Paper',
    rows: 1,
    rowsMax: 2,
    multiLine: true,
    className: 'multi-row',
    primaryText: 'Call For Paper',
  },
  {
    id: 4,
    name: 'speaker_description',
    hintText: ' Speaker Description',
    rows: 1,
    rowsMax: 2,
    multiLine: true,
    className: 'multi-row',
    primaryText: 'Speaker Description',
  },
  {
    id: 5,
    name: 'email',
    hintText: 'Email',
    multiLine: false,
    rows: 1,
    rowsMax: 1,
    primaryText: 'Email',
  },
  {
    id: 6,
    name: 'facebook_id',
    hintText: 'Facebook',
    rows: 1,
    rowsMax: 1,
    multiLine: false,
    primaryText: 'Facebook Link',
  },
  {
    id: 7,
    name: 'twitter_id',
    hintText: 'Twitter',
    rows: 1,
    rowsMax: 1,
    multiLine: false,
    primaryText: 'Twitter Link',
  },
  {
    id: 8,
    name: 'linkedin_id',
    hintText: 'Linkedin',
    rows: 1,
    rowsMax: 1,
    multiLine: false,
    primaryText: 'Linkedin Link',
  },
];

export default listField;
