const TOGGLE_EDIT_ACTIVITY_PAPER_FORM_MODAL =
  'cem-admin/schedule/TOGGLE_EDIT_ACTIVITY_PAPER_FORM_MODAL';
const TOGGLE_ADD_ACTIVITY_PAPER_FORM_MODAL =
  'cem-admin/schedule/TOGGLE_ADD_ACTIVITY_PAPER_FORM_MODAL';

const TOGGLE_ADD_ACTIVITY_TITLE_FORM_MODAL =
  'cem-admin/schedule/TOGGLE_ADD_ACTIVITY_TITLE_FORM_MODAL';
const TOGGLE_EDIT_ACTIVITY_TITLE_FORM_MODAL =
  'cem-admin/schedule/TOGGLE_EDIT_ACTIVITY_TITLE_FORM_MODAL';
const TOGGLE_DELETE_ACTIVITY = 'cem-admin/schedule/TOGGLE_DELETE_ACTIVITY';
const SET_EVENT_REQUESTED = 'cem-admin/conference/SET_EVENT_REQUESTED';
const SET_EVENT_SUCCESS = 'cem-admin/conference/SET_EVENT_SUCCESS';
const SET_EVENT_FAILURE = 'cem-admin/conference/SET_EVENT_FAILURE';

const CHECK_ERROR_REQUESTED = 'cem-admin/conference/CHECK_ERROR_REQUESTED';
const CHECK_ERROR_SUCCESS = 'cem-admin/conference/CHECK_ERROR_SUCCESS';
const CHECK_ERROR_FAILURE = 'cem-admin/conference/CHECK_ERROR_FAILURE';

const DELETE_SCHEDULE_IDS_REQUESTED =
  'cem-admin/conference/DELETE_SCHEDULE_IDS_REQUESTED';
const DELETE_SCHEDULE_IDS_SUCCESS =
  'cem-admin/conference/DELETE_SCHEDULE_IDS_SUCCESS';
const DELETE_SCHEDULE_IDS_FAILURE =
  'cem-admin/conference/DELETE_SCHEDULE_IDS_FAILURE';

export default {
  TOGGLE_ADD_ACTIVITY_PAPER_FORM_MODAL,
  TOGGLE_EDIT_ACTIVITY_PAPER_FORM_MODAL,
  TOGGLE_ADD_ACTIVITY_TITLE_FORM_MODAL,
  TOGGLE_EDIT_ACTIVITY_TITLE_FORM_MODAL,
  TOGGLE_DELETE_ACTIVITY,
  SET_EVENT_REQUESTED,
  SET_EVENT_SUCCESS,
  SET_EVENT_FAILURE,
  DELETE_SCHEDULE_IDS_REQUESTED,
  DELETE_SCHEDULE_IDS_SUCCESS,
  DELETE_SCHEDULE_IDS_FAILURE,
  CHECK_ERROR_REQUESTED,
  CHECK_ERROR_SUCCESS,
  CHECK_ERROR_FAILURE,
};
